#!/bin/bash

# Written by Mladen Martincevic <mladen.martincevic@gmail.com>
# Distributed under license GPLv3+ GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY. YOU USE AT YOUR OWN RISK. THE AUTHOR
# WILL NOT BE LIABLE FOR DATA LOSS, DAMAGES, LOSS OF PROFITS OR ANY
# OTHER KIND OF LOSS WHILE USING OR MISUSING THIS SOFTWARE.
# See the GNU General Public License for more details.

LOG_DIR='log'
TEMPLATES_DIR='templates'
GIT_HOOKS=(pre-commit commit-msg)
COMPOSER='./composer.phar'

fix_dir() {
    if [ -z "$1" ]
        then
            mkdir -m 775 $1
        else
            if [[ -d $1 ]]
                then
                    INFO=( $(stat -c "%a" $1) )
                    if [[ ${INFO[0]} != 775 ]] ; then
                        chmod -R 775 $1
                    fi
                else
                    mkdir -m 775 $1
            fi
    fi
}

setup_github() {
    if [[ -d ".git" ]] ; then
        for hook in "${GIT_HOOKS[@]}"; do
            echo "${hook}"
            cp "bin/"${hook} ".git/hooks"
        done
    fi
}

composer() {
    $COMPOSER update
}


